# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimate_TFestimate_main <- function(filename, MERGED_VAF_THRESHOLD, file_prefix, depth, VAF_output, estimate_output) {
    .Call(`_cfSNV_estimate_TFestimate_main`, filename, MERGED_VAF_THRESHOLD, file_prefix, depth, VAF_output, estimate_output)
}

filter_with_pileup_main <- function(fInput, fIntermediate, fOutputPass, fOutputCheck, fRecord, fTF, mergedVAFThreshold, SNPDatabase, depth) {
    .Call(`_cfSNV_filter_with_pileup_main`, fInput, fIntermediate, fOutputPass, fOutputCheck, fRecord, fTF, mergedVAFThreshold, SNPDatabase, depth)
}

genotype_genotype_main <- function(finput, foutputCall, tumorFraction, mergedVAFThreshold, depth, MIN_PASS_SUPPORT_COUNT) {
    .Call(`_cfSNV_genotype_genotype_main`, finput, foutputCall, tumorFraction, mergedVAFThreshold, depth, MIN_PASS_SUPPORT_COUNT)
}

ParseFile <- function(in_file_name, out_file_name, indel_file_name, depth, MIN_PASS_SUPPORT_COUNT) {
    invisible(.Call(`_cfSNV_ParseFile`, in_file_name, out_file_name, indel_file_name, depth, MIN_PASS_SUPPORT_COUNT))
}

machinelearn_extract_features_from_reads_filter_cluster <- function(inpath, outpath, sample_id, WINDOW) {
    .Call(`_cfSNV_machinelearn_extract_features_from_reads_filter_cluster`, inpath, outpath, sample_id, WINDOW)
}

